### ISSUE TITLE
Optimize `prod` maven profile for production

### ISSUE THREAD

**Issue by rapasoft** [rapasoft/footsign#11]
This would mean researching these topics:
- caching and compression of the static resources
- fine-tuning settings of embedded Tomcat

and so on...

**Comment by PeterCervienka** [comment]
I run Audit tool via Chrome above our application (intro page) and it recommends us to make this steps:

1. Combine external CSS (6)
   - There are multiple resources served from same domain. Consider combining them into as few files as possible.

2 Combine external JavaScript (6)
   - There are multiple resources served from same domain. Consider combining them into as few files as possible.
   - 6 JavaScript resources served from localhost.

3. Enable gzip compression (13)
   - Compressing the following resources with gzip could reduce their transfer size by about two thirds (~272 KB):

4. Leverage browser caching (17)
   - The following resources are explicitly non-cacheable. Consider making them cacheable if possible:
   - localhost/
   - normalize.css
   - bootstrap.min.css
   - main.css
   - selectize.bootstrap3.css
   - application.css
   - star-rating.min.css
   - jquery-2.1.3.min.js
   - bootstrap.min.js
   - selectize.js
   - graphs.js
   - application.js
   - star-rating.min.js
   - jsapi
   - icon-xsmall.jpg
   - foosball_intro.jpg
   - glyphicons-halflings-regular.woff2

**Comment by rapasoft** [comment]
Added minification of css and js resources (but no combining yet - all.css or all.js is missing)
Added GZIP compression but I need to figure out how to pass-it-through IIS which is served as proxy server
Cache is enabled as well, but not working via IIS :(
