### ISSUE TITLE
Add email notifications for planned matches

### ISSUE THREAD

**Issue by rapasoft** [rapasoft/footsign#15]
When user creates planned match with a specific players, add ability to send email notifications to them about the upcoming matches.

**Comment by rapasoft** [comment]
Add email notifications for these events:
![image](https://cloud.githubusercontent.com/assets/930301/6779422/1b6a1be6-d15c-11e4-94f3-572efd2d2ef1.png)

**Comment by PeterCervienka** [comment]
commit cd8d0d2. User can check or uncheck mails, which wants to receive in user profile. But we still need implemented this settings to controllers, where mails are sended.

**Comment by PeterCervienka** [comment]
feature is done: 97be56c
